springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  packages-to-scan: toy.blog.be

spring:
  config:
    import:
      - classpath:/encrypted.yml
