#spring:
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  h2:
#    console:
#      enabled: true
#
#  transaction:
#    default-timeout: 10
#


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  packages-to-scan: toy.blog.be


